[profile.default]
src = "src"
out = "out"
script = 'script'
test = 'test'
libs = ["node_modules", "lib"]
# solc_version = '0.8.15'
evm_version = "cancun"
auto_detect_solc = true
fs_permissions = [
    { access = 'read-write', path = './deployments/' },
    { access = 'write', path = './deployments/31337/' },
    { access = 'read', path = './deploy-config/' },
    { access = 'read', path = './broadcast/' },
    { access = 'read', path = './forge-artifacts/' },
    { access = 'read', path = './out' },
    { access = 'read', path = './script/deploy/' },
    { access = 'read-write', path = './' },
]

[profile.oz_5_0_2]
src = "src-oz_5_0_2"
out = "out-oz_5_0_2"
script = 'script-oz_5_0_2'
test = 'test-oz_5_0_2'
libs = ['lib-5_0_2']
solc_version = '0.8.25'
evm_version = "cancun"
ffi = true
ast = true
build_info = true
extra_output = ["storageLayout"]
fs_permissions = [
    { access = 'read-write', path = './deployments/' },
    { access = 'write', path = './deployments/31337/' },
    { access = 'read', path = './deploy-config/' },
    { access = 'read', path = './broadcast/' },
    { access = 'read', path = './forge-artifacts/' },
    { access = 'read', path = './out' },
    { access = 'read', path = './script/deploy/' },
    { access = 'read-write', path = './' },
]
[fmt]
ignore = ['generated/**/*.sol', "lib/**/*.sol"]
