[profile.default]
src = "src"
out = "out"
libs = ["node_modules", "lib"]
solc_version = '0.8.15'

# Test / Script Runner Settings
ffi = true
fs_permissions = [
    { access = 'read-write', path = './deployments/' },
    { access = 'read', path = './deploy-config/' },
    { access = "read", path = "./out" },
    { access = 'read', path = './script/deploy/' },
    { access = "read", path = "./" },
]

[fmt]
ignore = ['generated/**/*.sol', "lib/**/*.sol"]
