[profile.default]
src = "src"
out = "out"
script = 'script'
test = 'test'
libs = ["node_modules", "lib"]
# solc_version = '0.8.15'
auto_detect_solc = true

[profile.oz_5_0_2]
src = "src-oz_5_0_2"
out = "out-oz_5_0_2"
script = 'script-oz_5_0_2'
test = 'test-oz_5_0_2'
libs = ['lib-5_0_2']
solc_version = '0.8.20'
# auto_detect_solc = true

# Test / Script Runner Settings
ffi = true
# fs_permissions = [
#     # { access = "write", path = "/" },
#     { access = 'read-write', path = './deployments/' },
#     { access = 'read', path = './deploy-config/' },
#     { access = 'read', path = './broadcast/' },
#     { access = 'read', path = './forge-artifacts/' },
#     { access = "read", path = "./out" },
#     { access = 'read', path = './script/deploy/' },
#     { access = "read", path = "./" },
# ]

fs_permissions = [
    { access = 'read-write', path = './deployments/' },
    { access = 'read', path = './deploy-config/' },
    { access = 'read', path = './broadcast/' },
    { access = 'read', path = './forge-artifacts/' },
    { access = 'read', path = './out' },
    { access = 'read', path = './script/deploy/' },
    { access = 'read-write', path = './' },
]


[fmt]
ignore = ['generated/**/*.sol', "lib/**/*.sol"]
